version: "3"

services:
  db:
      container_name: pg_container
      image: postgres:14
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: femalegeek
      ports:
        - "5432:5432"
      volumes:
        - "my_dbdata:/var/lib/postgresql/data"
  redis:
    image: redis:4
    ports:
      - "6379:6379"
    volumes:
      - "./etc/redis.conf:/usr/local/etc/redis.conf"
volumes:
  my_dbdata: {}